INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (1, 1, 'Yes', 'question', 2);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (2, 1, 'No', 'question', 3);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (3, 2, 'Yes', 'product', 2);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (4, 2, 'No', 'product', 1);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (5, 3, 'Yes', 'question', 4);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (6, 3, 'No', 'product', 3);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (7, 4, '2', 'product', 4);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (8, 4, '4', 'question', 5);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (9, 5, 'Type 1', 'product', 6);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (10, 5, 'Type 2', 'product', 5);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (11, 6, 'Yes', 'question', 7);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (12, 6, 'No', 'product', 7);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (13, 7, 'Yes', 'question', 8);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (14, 7, 'No', 'question', 9);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (15, 8, 'Type 1', 'product', 10);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (16, 8, 'Type 2', 'product', 11);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (17, 9, 'Yes', 'question', 10);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (18, 9, 'No', 'question', 11);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (19, 10, 'Type 1', 'question', 29);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (20, 10, 'Type 2', 'question', 30);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (21, 11, 'Type 1', 'product', 35);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (22, 11, 'Type 2', 'question', 12);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (23, 12, 'Yes', 'product', 9);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (24, 12, 'No', 'product', 8);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (25, 13, 'Yes', 'question', 14);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (26, 13, 'No', 'question', 17);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (27, 14, 'Type 1', 'question', 15);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (28, 14, 'Type 2', 'question', 16);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (29, 15, '1/1', 'product', 14);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (30, 15, '1/3', 'product', 15);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (31, 16, '1/1', 'product', 12);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (32, 16, '1/3', 'product', 13);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (33, 17, 'Type 1', 'question', 18);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (34, 17, 'Type 2', 'question', 19);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (35, 18, '1/1', 'product', 18);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (36, 18, '1/3', 'product', 19);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (37, 19, '1/1', 'product', 16);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (38, 19, '1/3', 'product', 17);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (39, 20, 'Yes', 'question', 21);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (40, 20, 'No', 'question', 24);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (41, 21, 'Type 1', 'question', 22);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (42, 21, 'Type 2', 'question', 23);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (43, 22, '1/1', 'product', 30);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (44, 22, '1/3', 'product', 31);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (45, 23, '1/1', 'product', 28);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (46, 23, '1/3', 'product', 29);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (47, 24, 'Type 1', 'question', 25);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (48, 24, 'Type 2', 'question', 26);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (49, 25, '1/1', 'product', 25);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (50, 25, '1/3', 'product', 26);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (51, 26, '1/1', 'product', 24);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (52, 26, '1/3', 'product', 27);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (53, 27, 'Speech Intelligibility', 'question', 28);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (54, 27, 'Reverberation', 'product', 32);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (55, 28, 'Type 1', 'product', 33);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (56, 28, 'Type 2', 'product', 34);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (57, 29, '1/1', 'product', 14);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (58, 29, '1/3', 'product', 15);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (59, 30, '1/1', 'product', 12);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (60, 30, '1/3', 'product', 13);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (61, 31, '1', 'question', null);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (62, 31, '2', 'question', null);
INSERT INTO answers (answer_id, question_id, answer_text, node_type, node_id) VALUES (63, 31, '3 products', 'product', null);